# Generated by Django 3.0.10 on 2021-03-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning',
            old_name='group',
            new_name='group_model',
        ),
    ]
