# Generated by Django 3.0.10 on 2021-03-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0002_auto_20210330_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='department',
            field=models.CharField(max_length=3),
        ),
    ]
