# Generated by Django 3.0.10 on 2021-04-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0003_auto_20210330_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writedata',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
