# Generated by Django 3.0.10 on 2021-03-30 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_data', '0002_djgroupmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djmodel',
            name='group',
        ),
    ]
