# Generated by Django 3.0.10 on 2021-03-30 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_data', '0003_remove_djmodel_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='djmodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dj_data.DJGroupModel'),
        ),
    ]
